### ISSUE TITLE
Would you be interested in creating an organization

### ISSUE THREAD

**Issue by nils-a** [juro-org/MediatR.LightCore#9]
Hey there, nice project.

I also have two projects integrating LightCore into other projects: [Quartz.LightCore](https://github.com/nils-org/Quartz.LightCore) and [Topshelf.LightCore](https://github.com/nils-org/Topshelf.LightCore).

Would you be interested in forming a GitHub organization (I was thinking of `LightCore-Integrations`) to "group" the three projects?

**Comment by JuergenRB** [comment]
I thi
